#Test against this version of Node.js
environmentL
  matrix:
    #node.js
  - nodejs_version: "8"

  #Install scripts. (runs after repo cloning)
  install:
    #Get the latest stable version of Node.js or io.js
    - ps: Install-Prudoct node $env:nodejs_version
    #install modules
    - npm install

  #Post-install test scripts.
  test-script:
    #Output useful info for debugging
    - node --version
    - npm --version
    #run tests
    - npm test


    #Don't actually build.
    build: off